# -*- coding: utf-8 -*-
"""andPerceptron.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK_gHiGyM7m8xn8Ho5hpVPIpTqUz4Apz
"""



from numpy import array, dot, random
from random import choice

def hardlim(val):
    return (0 if val < 0 else 1)

d = [
    (array([1,0,0]), 0),
    (array([1,0,1]), 0),
    (array([1,1,0]), 0),
    (array([1,1,1]), 1),
]

n = 50
lr = 0.01
w = random.rand(3)
E=1

while E != 0:
    E=0
    for i in range(n):
        x, di = choice(d)
        yi = dot(w, x)
        ei = di - hardlim(yi)
        w += lr * ei * x
        E += ei ** 2
        print("{}: {} -> {}".format(x[1:3], yi, hardlim(yi)))
        print(w)
        print("\n")